"use client";

import { EChart } from "@/components/echart";
import type { EChartsOption } from "echarts";

export default function Page() {
  const data = [
    [1, -1],
    [2, 9],
    [3, 12],
    [4, 7],
    [5, 12],
    [6, 16],
    [7, 12],
    [8, 21],
    [9, 20],
    [10, 15],
    [11, 20],
    [12, 21],
    [13, 16],
    [14, 20],
    [15, 35],
    [16, 22],
    [17, 30],
    [18, 26],
    [19, 30],
    [20, 31],
    [21, 25],
    [22, 23],
    [23, 31],
    [24, 37],
    [25, 37],
    [26, 42],
    [27, 40],
    [28, 39],
    [29, 46],
    [30, 47],
    [31, 43],
    [32, 44],
    [33, 47],
    [34, 49],
    [35, 54],
    [36, 53],
    [37, 50],
    [38, 53],
    [39, 70],
    [40, 60],
    [41, 54],
    [42, 60],
    [43, 65],
    [44, 60],
    [45, 67],
    [46, 55],
    [47, 60],
    [48, 61],
    [49, 72],
  ];

  const chart1: EChartsOption = {
    xAxis: {
      type: "value" as const,
    },
    yAxis: { type: "value" as const },
    series: [
      {
        data: data,
        type: "scatter",
        symbolSize: 8,
      },
    ],
  };

  return (
    <div className="w-full px-8">
      <h1 className="mb-2 text-4xl font-bold">Linear Regression</h1>

      <p className="mt-2 text-lg text-gray-500 dark:text-gray-400">
        A simple supervised learning algorithm for predicting continuous values.
      </p>
      <h2 className="mb-4 mt-4 text-2xl font-bold">How do you fit a line?</h2>

      <p className="mt-4">
        It's a deceptively deep question. Let's say you have a set of points
        that looks like this:
      </p>

      <div className="mt-10 flex justify-center">
        <div className="w-full max-w-[1000px]">
          <EChart option={chart1} />
        </div>
      </div>

      <p className="mt-4">
        And you want to fit a line to these points. How do you do that?
      </p>

      <p className="mt-4">Well, you could try to eyeball it.</p>

      <div className="mt-10 flex justify-center">
        <div className="w-full max-w-[1000px]">
          <EChart
            option={{
              xAxis: { type: "value" as const },
              yAxis: { type: "value" as const },
              series: [
                {
                  data: data,
                  type: "scatter",
                  symbolSize: 8,
                },
                {
                  data: Array.from({ length: 49 }, (_, i) => [
                    i + 1,
                    1.2 * (i + 1) + 3.8,
                  ]),
                  type: "line",
                  symbol: "none",
                },
              ],
            }}
          />
        </div>
      </div>

      <p className="mt-4">Not the worst, but it's pretty arbitrary.</p>

      <p className="mt-4">This problem comes up a lot.</p>

      <p className="mt-4">
        It was first solved by Adrien-Marie Legendre in 1805, but I use the word
        solved extremely loosely.
      </p>

      <p className="mt-4">
        Since, then it's been tackled by Carl Friedrich Gauss, Pierre-Simon
        Laplace, Francis Galton, Karl Pearson, Andrey Markov, Ronald Fisher, and
        many others in the modern era.
      </p>

      <p className="mt-4">
        Legendre and Gauss both independently came up with the method of least
        squares, which is the basis of linear regression.
      </p>
      <p className="mt-4">
        The essential idea is that you find the line that minimizes the sum of
        the squared distances between the points and the line.
      </p>
      <p className="mt-4">
        That is to say, if you imagine that these points were generated by some
        linear function (where linear in this case simply means producing a
        line) and then some random noise was added to each point, then the line
        you fit will be the one that minimizes the average squared error.
      </p>
    </div>
  );
}
